#pragma listinclude  /* List this file */
/*#pragma diagnostic(0)/ * List all remarks, warnings and err msg */
#pragma searchinclude(h\,filters\)
#pragma noextend     /* Recognizes Intel extensions to ANSI C */
#pragma model(KC)    /* Processor model - only KB compiler at present */
/*#pragma optimize(0)  / * 0 1 or 2 not 3 */
#pragma regconserve  /* register optimization */
#pragma registers(32)/* number of register that can be used */
#pragma print        /* Produce a print file */
#pragma notype         /* include type information for debugging */
/***** general *****/
#pragma reentrant    /* Make all functions reentrant */
/*#pragma nodebug        / * Add debug information */
#pragma code          /* List code */
